### ISSUE TITLE
The taxonomy term doesn't stick when the post in the admin is reloaded

### ISSUE THREAD

**Issue by slocker3** [happyprime/latest-custom-posts#1]
When the blocks are set in a post all work as expected on the front and admin views. However, once the admin page has been refreshed or navigated away from and reloaded the blocks lose their _terms_. If the post is _Updated_ all blocks save without a _term_.

**Comment by jeremyfelt** [comment]
This should be good to go. The attribute for the `termID` was being saved in the block markup as a string even though the attribute is an integer. Gutenberg would then strip that attribute on a reload because it didn't match the expected type. Things are now forced to `Number( termID )` when the attribute is set.
